remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme

title: HCI Research Group at the University of Bergen
description: 
tagline: HCI Research Group

show_downloads: false

github:
  is_project_page: false